#!/bin/sh
alias j='z'
alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# tmux
alias \
    tn="tmux -u -f ~/.config/tmux/tmux.conf new" \
    ta="tmux -u -f ~/.config/tmux/tmux.conf attach"

alias magit="nvim -c MagitOnly"

# php
alias sf=symfony

#tezos
alias tc=octez-client
alias mc="octez-client --mode mockup --base-dir /tmp/mockup"
# alias refresh-ligo="docker rmi -f $(docker images 'ligolang/ligo' -a -q)"
alias refresh-sandbox="docker rmi -f $(docker images 'oxheadalpha/flextesa:latest' -a -q)"
alias rmi="docker rmi -f \$(docker images -qf dangling=true)"
alias '?'=duck
alias '??'=google
alias lg=lazygit

alias q="query-json"

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	alias ls='ls -G'
	;;

Linux)
	alias ls='ls --color=auto'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac

alias lf="lfub"
