#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export MANPAGER='lvim --appimage-extract-and-run +Man!'
export MANWIDTH=999
eval "$(fnm env)"
eval "$(zoxide init zsh)"
export DENO_INSTALL="/home/steven/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"
export PATH="$HOME/.local/java/jar:$PATH"
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
